### ISSUE TITLE
Get ID by character name

### ISSUE THREAD

**Issue by jeicho123** [seanbreckenridge/mal-id-cache#8]
Do you know if there's a way to get ID of character by character name. Looking at the Jikan API doc, a lot of the endpoints is accessible only if you know the ID which isn't really practical..

**Comment by purarue** [comment]
Not really related to Jikan and characters haven't been updated in years here, so nothing here

Can ask in the [jikan discord](https://discord.com/invite/4tvCr36) but pretty sure there is an endpoint

https://docs.api.jikan.moe/#tag/characters/operation/getCharactersSearch
